_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 35
                - 55
            "4": 3.12.4
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
batch_size:
    value: 128
clip_range:
    value: 0.2
data_dir:
    value: processed_data
ent_coef:
    value: 0.01
eval_episodes:
    value: 5
eval_freq:
    value: 5000
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
initial_balance:
    value: 10
learning_rate:
    value: 0.0005
max_position:
    value: 50
n_epochs:
    value: 5
n_steps:
    value: 1024
save_dir:
    value: fast_models
total_timesteps:
    value: 250000
transaction_fee:
    value: 0.002
