_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[-0.00707071 -0.00707071  0.         -0.00590693  0.00213162  0.
          -0.00512236  0.00707071  0.          0.          0.          0.        ]]
_last_original_obs:
    value: |-
        [[-0.9999992  -0.9999989   0.         -0.73212856  0.21819821  0.
          -0.59648436  1.          0.          0.          0.          0.        ]]
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x71019083ab10>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 250000
_vec_normalize_env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x7101997ab8f0>
_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.12.4
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Discrete(4)
algo:
    value: PPO
batch_size:
    value: 128
clip_obs:
    value: 5
clip_range:
    value: 0.1
clip_range_vf:
    value: None
clip_reward:
    value: 5
data_dir:
    value: processed_data
device:
    value: cuda
ent_coef:
    value: 0.005
env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x7101997ab8f0>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
eval_episodes:
    value: 5
eval_freq:
    value: 2500
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
initial_balance:
    value: 10
learning_rate:
    value: 3e-05
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7101995ffe20>
max_grad_norm:
    value: 0.5
max_position:
    value: 15
n_envs:
    value: 1
n_epochs:
    value: 5
n_steps:
    value: 2048
net_arch:
    value:
        pi:
            - 64
            - 64
        vf:
            - 64
            - 64
normalize_advantage:
    value: "True"
normalize_observations:
    value: true
normalize_rewards:
    value: true
num_timesteps:
    value: 0
observation_space:
    value: Box(-5.0, 5.0, (12,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=12, out_features=64, bias=True)
              (1): ReLU()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): ReLU()
            )
            (value_net): Sequential(
              (0): Linear(in_features=12, out_features=64, bias=True)
              (1): ReLU()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): ReLU()
            )
          )
          (action_net): Linear(in_features=64, out_features=4, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''net_arch'': {''pi'': [64, 64], ''vf'': [64, 64]}, ''activation_fn'': <class ''torch.nn.modules.activation.ReLU''>, ''optimizer_class'': <class ''torch.optim.adam.Adam''>, ''optimizer_kwargs'': {''eps'': 1e-05, ''weight_decay'': 1e-05}}'
reward_scaling:
    value: 1
risk_free_rate:
    value: 5.479452054794521e-05
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x710198b02930>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
save_dir:
    value: models
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1737480222040717148
target_kl:
    value: None
tensorboard_log:
    value: ./runs/1737480221
total_timesteps:
    value: 250000
transaction_fee:
    value: 0.002
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
