_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
algorithm:
    value: PPO
eval_freq:
    value: 10000
initial_balance:
    value: 10
max_position:
    value: 50
total_timesteps:
    value: 1000000
